#ifndef CCTOOLS_COMPAT_TARGET_CONDITIONALS_H
#define CCTOOLS_COMPAT_TARGET_CONDITIONALS_H
#define TARGET_OS_OSX 0
#define TARGET_OS_MAC 0
#define TARGET_OS_IPHONE 0
#define TARGET_OS_SIMULATOR 0
#define TARGET_OS_DRIVERKIT 0
#endif
